### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by memheldp** [JaouherK/streamDeck-weatherPlugin#30] opened 2021-10-29 08:02 UTC
Hello,
I installed the Weather plugin on an updated software Streamdeck XL, I tried both weather provider, creating API key, and nothing appears.
Thank you for your advice.
Regards,
Pierre

**Comment by JaouherK** [comment] 2022-03-21 21:32
The issue is already resolved and will be released in the next version

**Closed by JaouherK** 2022-03-21 21:32 UTC
Labels: bug, Validation required
