### ISSUE TITLE
Error fetching data from provider after updated version

### ISSUE THREAD

**Issue by drewmatthews** [JaouherK/streamDeck-weatherPlugin#26] opened 2021-07-27 18:01 UTC
The app just stopped working on my stream deck. 

I've double-checked my API key and restarted stream deck etc. Every time I press the button I just get the Triangle ! and then just the Weather logo again.

**Comment by bartnd** [comment] 2021-08-18 20:28
Had the same issue, but after making a sample request to the API url it started feeding data. 
I had originally used the wrong city format (I added state code as well) but even after removing the state and only listing the city (which ended up being successful) I would still see the green triangle.

**Comment by JaouherK** [comment] 2022-01-11 18:38
Dear @drewmatthews and @bartnd 
Thanks for reporting this bug 👍 
 Do you still face the issue? can you please provide me with the provider causing this?

**Comment by bartnd** [comment] 2022-01-11 18:52
@JaouherK I haven't had the issue since my report. I haven't needed to make any additional requests from the command line since my first report. I'm using the Open Weather provider. 

When I first start my computer in the morning, I _believe_ that I need to press the button for the weather to start displaying (otherwise it will display the 'weather' icon) though I usually don't let it sit to see if it connects on it's own. I can try leaving it for 10-15 minutes without pressing to see if it updates automatically; perhaps the initial request is tied to the fetch frequency setting (which I have set to 10 minutes)?

**Comment by drewmatthews** [comment] 2022-01-11 19:24
@JaouherK It's been so long and the plugin wasn't working that I just stopped using it on my Stream Deck. I just reinstalled it this morning and it seems to work again. But since it had been so long without a response I figured things were just not being worked on.

**Comment by JaouherK** [comment] 2022-01-11 19:28
@drewmatthews I had some personal issues that I wasn't able to check on it.
I am now trying to recover as much as possible the open issues to release a new version with fixes and feature requests.
@bartnd That would be great to have some test cases :)

**Comment by bartnd** [comment] 2022-01-11 21:36
@JaouherK I shutdown Windows and powered back on to fully repro the issue. I left it running for ~30 minutes and still displaying 'Weather' screen (in a Disney-like font). After pressing the button, the weather loads without issue.

**Comment by JaouherK** [comment] 2022-03-21 21:29
The issue is already resolved and will be released in the next version

**Closed by JaouherK** 2022-03-21 21:29 UTC
Labels: bug, Validation required
